PR cambios pedidos
cedir/react-redux-poc pull request #1
Opened 2016-11-02 00:01 UTC by jiaguilera

@walterbrunetti me re copé con el react-redux! :nerd_face: y hice todo esto:
- cambios que hacen que vuelva a andar el todo list
- refactoriza componentes genéricos [reutilizables]: List y ListItem (se mueven a app/components)
- refactoriza instancia de estos componentes para el Todo list: TodoList y TodoItem (se mueven a todo/components)
- elimina propiedad "todo" extra del estado
- mueve el estado inicial al valor por defecto del reducer
- etc

fijate que te parecen... a mi me gustó como va quedando :)

2016-11-02 15:04 UTC, walterbrunetti commented
@jiaguilera muy buenos que te hayas copado! Te deje algunos comentarios aunque todavia no termine el code review, mas tarde lo sigo.
De todos modos excelente PR!! Esto va muy bien encaminado, estoy muy contento :)
En cuanto cerremos esta PR, creo que estamos en condiciones de empezar con la app real.
![giphy 1](https://cloud.githubusercontent.com/assets/2583662/19934131/64990412-a0f4-11e6-8d00-ce648f85067b.gif)

2016-11-16 16:27 UTC, walterbrunetti requested changes

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/app/components/List.js
> +export const List = ({ items, generator }) => ( <ul> {items.map(generator)} </ul> );
@jiaguilera este componente es algo que se puede usar global en caulquier app para distintos tipos de listas? Sino creo que deberia ir dentro de todo/components

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/app/components/ListItem.js
> +export const ListItem = ({ display, completed, deleteItem, completeItem }) => {
Este item parece que aplica solo a Todo, sobre todo por las acciones no creo que sea reutilizable. Por eso me parece que debira ir a los components de Todo. Si estoy confundido avisame :)

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/app/configureStore.js
> +export default function configureStore() {
@jiaguilera  pregunta, hay alguna ventaja en no tener un initial state? Por que si o no tenerlo?
Se me ocurre que si uno quisiera tener un paneo de la aplicacion podria ver la estructura del initialState, pero no se que otra ventaja podria tener.

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/todo/Todo.js
> +      <TodoList/>
esto quedo muy bonito :)

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/todo/components/TodoItem.js
> +import React, { PropTypes } from 'react';
me parece que el TodoItem podria ir en el mismo archivo que el TodoList para simplificar. De todos modos no me parece mal.

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/todo/components/TodoList.js
> +export const TodoList = connect(
@jiaguilera esto no lo entendi muy bien..
![puede--darme-dinero](https://cloud.githubusercontent.com/assets/2583662/19933690/13c36d8a-a0f3-11e6-8564-55269e13ca44.jpg)

me parece mejor separar esto en dos pasos: uno para crear los objetos mapStateToProps y mapDispatchToProps, y el otro para llamar al connect, pero seguramente me estoy perdiendo de algo, si podes comentame como funciona esto.

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/todo/TodoReducers.js
> +        items: state.items.slice(0,action.index)
no entiendo bien por que usar slice aca?
Yo haria una copia de state.items y usaria el index para cambiar completed a true, este codigo me resulta dificil de seguir.

2016-11-16 16:27 UTC, walterbrunetti commented on src/js/todo/TodoReducers.js
> +        items: state.items.slice(0,action.index)
creo que este codigo se podria mejorar...algo asi??

```
items = [].concat(state.todo.items);
items.splice(action.index, 1);
return Object.assign({}, state, {todo: {items: items}});
```

2016-11-16 22:02 UTC, jiaguilera commented on src/js/app/components/List.js
> +export const List = ({ items, generator }) => ( <ul> {items.map(generator)} </ul> );
@walterbrunetti  la idea de los componentes en app/ es que son componentes los suficientemente abstractos como para ser usados una y otra vez en toda la aplicación.

2016-11-16 22:10 UTC, jiaguilera commented on src/js/app/components/ListItem.js
> +export const ListItem = ({ display, completed, deleteItem, completeItem }) => {
@walterbrunetti si, tenés razón, el nombre de las acciones lo atan bastante al dominio del problema y eso nos da la pauta de que no es lo suficientemente abstracto para ser global... muy buen comentario!

2016-11-16 22:14 UTC, jiaguilera commented on src/js/app/configureStore.js
> +export default function configureStore() {
@walterbrunetti la verdad que lo hice asi porque el flaco que hizo redux (en los videos lo hace asi).
Lo que se me ocurre que es positivo en este enfoque es que si queres cambiar el reducer, no necesitas modificar nada... el mismo reducer construye la versión inicial del "pedacito" de estado que administra. Pero es discutible...

2016-11-16 22:15 UTC, jiaguilera commented on src/js/todo/Todo.js
> +      <TodoList/>
@walterbrunetti react-redux es bonito... :nerd_face:

2016-11-16 22:28 UTC, jiaguilera commented on src/js/todo/TodoReducers.js
> +        items: state.items.slice(0,action.index)
El problema es que así mutás el estado... concat no crea una copia nueva de los elementos, solamente crea una nueva lista de referencias a los existentes... 

![screenshot from 2016-11-16 19-24-12](https://cloud.githubusercontent.com/assets/1071404/20368396/9d949378-ac32-11e6-8fc0-32d578ad0c3b.png)

2016-11-16 22:37 UTC, jiaguilera commented on src/js/todo/TodoReducers.js
> +        items: state.items.slice(0,action.index)
@walterbrunetti si, la forma que yo lo puse es más funcional, supongo que por costumbre, pero las dos son válidas

2016-11-16 22:38 UTC, jiaguilera commented on src/js/todo/components/AddTodo.js
> +      <form onSubmit={e => {
@walterbrunetti a esta parte me parece que tenemos que ponerle un poco más de "amor"

2016-11-16 22:45 UTC, jiaguilera commented on src/js/todo/components/TodoList.js
> +export const TodoList = connect(
@walterbrunetti lo unico raro que hay aca es la función "generator" que es una especie de template que le pasamos a List para que sepa como son los items del TodoList.
En este caso a connect, le pasamos su primer argumento (mapStateToProps) pero no hay mapDispatchToProps porque no se necesita. Parece un trabalenguas, no? :yum:

2016-11-16 22:46 UTC, jiaguilera commented on src/js/todo/components/TodoList.js
> +export const TodoList = connect(
@walterbrunetti de todas formas, se puede hacer en partes si te parece mas claro, la idea es que nos resulte cómodo interpretar el código...

2016-11-21 23:38 UTC, jiaguilera commented on src/js/app/components/RemovableListItem.js
> +export class RemovableListItem extends React.Component {
@walterbrunetti este componente reemplaza al ListItem que no era lo suficientemente abstracto como para poder ser un componente general. Este pinta mucho mejor!

2016-11-24 00:05 UTC, walterbrunetti approved these changes

2016-11-24 19:11 UTC, merged